const webDevRepositories = [
  {
    title: "MDN Web Docs",
    description:
      "MDN Web Docs is an open-source, collaborative project that documents web technologies including CSS,HTML,JavaScript, and Web APIs. Alongside detailed reference documentation, we provide extensive learning resources for students and beginners getting started with web development...",
    url: "https://github.com/mdn/content",
  },
  {
    title: "freeCodeCamp",
    description:
      "freeCodeCamp.org is a friendly community where you can learn tocode for free. It is run by a donor-supported 501(c)(3) charity to help millions of busy adults transition into tech. Our community has already helped more than 40,000 people get their first developer job...",
    url: "https://github.com/freeCodeCamp/freeCodeCamp",
  },
  {
    title: "Codecademy Docs",
    description:
      "Codecademy Docs is a collection of information for all things code...",
    url: "https://github.com/Codecademy/docs",
  },
  {
    title: "GitHub Docs",
    description:
      "This repository contains the documentation website code and Markdown source files for docs.github.com. GitHub's Docs team works on pre-production content in a private repo that regularly syncs with this public repo...",
    url: "https://github.com/github/docs",
  },
  {
    title: "Docusaurus",
    description:
      "Docusaurus is a project for building, deploying, and maintaining open source project websites easily..",
    url: "https://github.com/facebook/docusaurus",
  },
  {
    title: "First Contributions",
    description:
      "This repo aims to simplify and guide the way beginners make their first contribution. If you are looking to make your first contribution, follow the steps below...",
    url: "https://github.com/firstcontributions/first-contributions",
  },
  {
    title: "balenaCloud Docs",
    description:
      "Documentation for the balenaCloud platform lives here. This repo intends to provide our public-facing documentation. To view the documentation generated by this repo, one could either run locally or view the hosted version...",
    url: "https://github.com/balena-io/docs",
  },
  {
    title: "Awesome React",
    description:
      "A collection of awesome things regarding the React ecosystem...",
    url: "https://github.com/enaqx/awesome-react",
  },
  {
    title: "Storybook",
    description:
      "Storybook is a frontend workshop for building UI components and pages in isolation. Thousands of teams use it for UI development, testing, and documentation...",
    url: "https://github.com/storybookjs/storybook",
  },
  {
    title: "Prettier",
    description:
      "Prettier is an opinionated code formatter. It enforces a consistent style by parsing your code and re-printing it with its own rules that take the maximum line length into account, wrapping code when necessary...",
    url: "https://github.com/prettier/prettier",
  },
  {
    title: "Novu",
    description:
      "The ultimate service for managing multi-channel notifications with a single API...",
    url: "https://github.com/novuhq/novu",
  },
];

const jsLibAndFrameworks = [
  {
    title: "React",
    description:
      "React is a JavaScript library for building user interfaces...",
    url: "https://github.com/facebook/react",
  },
  {
    title: "React Native",
    description:
      "React Native brings React's declarative UI framework to iOS and Android. With React Native, you use native UI controls and have full access to the native platform...",
    url: "https://github.com/facebook/react-native",
  },
  {
    title: "Angular",
    description:
      "Angular is a development platform for building mobile and desktop web applications using TypeScript/JavaScript and other languages...",
    url: "https://github.com/angular/angular",
  },
  {
    title: "Bootstrap",
    description:
      "The most popular HTML, CSS, and JavaScript framework for developing responsive, mobile first projects on the web...",
    url: "https://github.com/twbs/bootstrap",
  },
  {
    title: "Apache Arrow",
    description:
      "Apache Arrow is a development platform for in-memory analytics. It contains a set of technologies that enable big data systems to process and move data fast...",
    url: "https://github.com/apache/arrow",
  },
];

const machineLearningAndAI = [
  {
    title: "MindsDB",
    description:
      "MindsDB's AI SQL Server enables developers to build AI tools that need access to real-time data to perform their tasks...",
    url: "https://github.com/mindsdb/mindsdb",
  },
];

const BioInformatics = [
  {
    title: "BioDrop",
    description:
      "A platform where people in tech can have a single hub to showcase their content in order to accelerate their career, whilst contributing to an Open Source project and being part of a community that has a say in where the project is going...",
    url: "https://github.com/EddieHubCommunity/BioDrop",
  },
];

const CrossPlatformAppDevelopment = [
  {
    title: "Flutter",
    description:
      "Flutter is a cross-platform UI toolkit that allows developers to create natively compiled applications for mobile, web, and desktop from a single codebase...",
    url: "https://github.com/flutter/flutter",
  },
];

export { webDevRepositories, jsLibAndFrameworks, machineLearningAndAI, BioInformatics, CrossPlatformAppDevelopment }